### PR TITLE
Add updates page

### PR DESCRIPTION
**Pull request by frankieroberto**
This page lists all the changes from the [CHANGELOG](https://github.com/nhsuk/nhsuk-prototype-kit/blob/main/CHANGELOG.md) in major and minor releases since 4.0.0, a similar way to the [Service manual updates page](https://service-manual.nhs.uk/whats-new/updates).

The main aim is to be more easily findable than the changelog, and in a more accessible form.

The changelog would remain as the more exhaustive and developer-focused documentation.

It’s only linked to from the footer initially. We could have a separate "What’s new" page above it (like the [Service manual What’s new page](https://service-manual.nhs.uk/whats-new)) which includes the most recent release notes, as well as any other recent major updates to the documentation site (eg new guides), links to blog posts, links to NHS frontend updates, and anything else we might want to call out?

Part of #101

### Screenshot

Screenshot of the new Updates page

### CODE REVIEW

**Comment by vickytnz** [comment]
This looks good, my main questions will be:
1. do we also include change to the document site here (I assume so) and if so should we make this clear in the lede for example: 'Changes made in each release of the prototype kit and the documentation'?
2. will we need to decide what counts as version changes for the document site to justify notes?

**Review by vickytnz — APPROVED** [review]
This looks good, my main questions will be:

1. do we also include change to the document site here (I assume so) and if so should we make this clear in the lede for example: 'Changes made in each release of the prototype kit and the documentation'?
2. will we need to decide what counts as version changes for the document site to justify notes?

**Comment by frankieroberto** [comment]
> 1. do we also include change to the document site here (I assume so) and if so should we make this clear in the lede for example: 'Changes made in each release of the prototype kit and the documentation'?
> 2. will we need to decide what counts as version changes for the document site to justify notes?

I was thinking not - that this page would purely be about releases of the kit (like the CHANGELOG but more accessible and within the site rather than on GitHub).

Changes to the documentation site aren’t versioned in the same way, and probably usually don’t need to be called out (continuous improvement and all that). But for major changes or new features we could mention them on a "What’s new" page which sits above the Updates page?

**Comment by vickytnz** [comment]
Maybe add notes on this page about what is counted and not (for example we won't include typos or entirely internal facing)

**Review by vickytnz — APPROVED** [review]
Agree with changes. After initially thinking we should be more explicit about what's in and out with updates, I am now in two minds about this as maybe it can be covered in whatever instructions are available for doing a new release of the prototype kit and how to release the change notes. 

That said, if these don't exist then the updates page could have a details text maybe with

v What is and is not included in update notes
> Update notes include details that affect the user experience of either using the kit or its document website. They do not include internal-only processes or minor updates such as fixing spelling mistakes.

**Comment by frankieroberto** [comment]
@vickytnz sounds good. I’ll add a note to the release guide about updating this page separately.

**Pull request merged**
